### ISSUE TITLE
Command based token support

### ISSUE THREAD

**Issue by macat** [felixfbecker/PSKubectl#54]
AWS EKS relies on getting the user token from the `aws eks get-token` command. 

In the ~/.kubectl/config:
```yaml
users:
- name: arn:aws:eks:us-east-1:ID:cluster/clustertname
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - --region
      - us-east-1
      - eks
      - get-token
      - --cluster-name
      - clustername
      command: aws
```

PSKubectl does not pick up the user configured by AWS and it defaults to `"system:anonymous"`.

Also, when I use `Use-KubeContext <contextname>`, it deletes the exec block from the config.

Is there a way to make this work or it requires changes in the kube client? I was trying to trace how this config gets picked up, but didn't get too far.

**Comment by felixfbecker** [comment]
This only needs support in https://github.com/tintoy/dotnet-kube-client
cc @tintoy

**Comment by felixfbecker** [comment]
Also interesting the GCP auth is command-based too but works:
```yaml
- name: gke_sourcegraph-dev_us-central1-f_dot-com
  user:
    auth-provider:
      config:
        access-token: REDACTED
        cmd-args: config config-helper --format=json
        cmd-path: /Users/felix/google-cloud-sdk/bin/gcloud
        expiry: "2019-09-21T02:28:54Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```
